# -----------------------------------------------------------------------------
# Nginx Events Configuration
# -----------------------------------------------------------------------------

events {

    # Number of simultaneous connections.
    worker_connections 1024;
}

# -----------------------------------------------------------------------------
# HTTP Configuration
# -----------------------------------------------------------------------------

http {


    # -------------------------------------------------------------------------
    # Backend Server Routing
    # -------------------------------------------------------------------------

    server {

        # Nginx listens on port 80.
        listen 80;


        # ---------------------------------------------------------------------
        # Reverse Proxy Route
        # ---------------------------------------------------------------------

        location / {


            # Forward request to FastAPI backend.
            proxy_pass http://fastapi:8000;


            # Preserve original request information.
            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

    }

}